/**
 * Self-hosts the four families the design system names.
 *
 * Spec section 9 requires fonts self-hosted with font-display: swap and
 * preloaded. Linking fonts.googleapis.com would cost a second connection
 * before the first paint and hand every visitor's IP to a third party, which
 * is the wrong default for a site collecting health data.
 *
 * Run: npm run fonts --workspace=frontend
 *
 * Writes woff2 files into public/fonts and generates src/styles/fonts.css.
 * Both are committed, so a clone builds without network access.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath, URL as NodeURL } from 'node:url';

const here = (p) => fileURLToPath(new NodeURL(p, import.meta.url));
const FONT_DIR = here('../public/fonts');
const CSS_OUT = here('../src/styles/fonts.css');

// A modern desktop UA is required or the API serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

/**
 * Only the subsets this product actually renders. Latin for the interface,
 * devanagari and gujarati because patient and professional names contain them
 * even in an English interface (spec 5.3). The Noto families carry no latin
 * subset: latin always resolves to Instrument Sans earlier in the stack.
 *
 * Weights are requested as ranges, not as a list.
 *
 * All four are variable fonts. Asking for `400;500` makes Google serve the
 * whole variable file once per weight - two identical 129 KB downloads for
 * Newsreader alone. Asking for `400..500` serves it once, with a
 * `font-weight: 400 500` range on the face, and the browser interpolates.
 */
const FAMILIES = [
  { family: 'Newsreader', axis: 'opsz,wght', spec: '6..72,400..500', subsets: ['latin', 'latin-ext'] },
  { family: 'Instrument Sans', axis: 'wght', spec: '400..600', subsets: ['latin', 'latin-ext'] },
  { family: 'Noto Sans Devanagari', axis: 'wght', spec: '400..500', subsets: ['devanagari'] },
  { family: 'Noto Sans Gujarati', axis: 'wght', spec: '400..500', subsets: ['gujarati'] },
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function fetchCss({ family, axis, spec }) {
  const url =
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:${axis}@${spec}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${family}: Google Fonts returned ${res.status}`);
  return res.text();
}

/** Splits the CSS into one record per @font-face, keeping the unicode-range. */
function parseFaces(css, family) {
  const faces = [];
  let currentSubset = 'latin';
  for (const line of css.split('\n')) {
    const comment = line.match(/^\/\*\s*([a-z-]+)\s*\*\/$/);
    if (comment) currentSubset = comment[1];
    faces.push({ line, subset: currentSubset });
  }

  const blocks = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  for (const [, subset, body] of css.matchAll(re)) {
    const weight = body.match(/font-weight:\s*([^;]+);/)?.[1].trim();
    const style = body.match(/font-style:\s*([^;]+);/)?.[1].trim() ?? 'normal';
    const src = body.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
    if (!src || !weight) continue;
    blocks.push({ family, subset, weight, style, src, range });
  }
  void faces;
  return blocks;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const all = [];

  for (const entry of FAMILIES) {
    process.stdout.write(`${entry.family} ... `);
    const css = await fetchCss(entry);
    const faces = parseFaces(css, entry.family).filter((f) => entry.subsets.includes(f.subset));
    if (faces.length === 0) throw new Error(`${entry.family}: no matching subsets in response`);

    for (const face of faces) {
      const weightTag = face.weight.includes(' ') ? 'var' : face.weight;
      const name = `${slug(entry.family)}-${face.subset}-${weightTag}.woff2`;
      const res = await fetch(face.src, { headers: { 'User-Agent': UA } });
      if (!res.ok) throw new Error(`${name}: ${res.status}`);
      const bytes = Buffer.from(await res.arrayBuffer());
      await writeFile(`${FONT_DIR}/${name}`, bytes);
      all.push({ ...face, file: name, bytes: bytes.length });
    }
    process.stdout.write(`${faces.length} face(s)\n`);
  }

  const css = [
    '/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */',
    '/* Self-hosted so the first paint needs no third-party connection. */',
    '',
    ...all.map((f) =>
      [
        '@font-face {',
        `  font-family: '${f.family}';`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${f.file}') format('woff2');`,
        f.range ? `  unicode-range: ${f.range};` : null,
        '}',
        '',
      ]
        .filter(Boolean)
        .join('\n'),
    ),
  ].join('\n');

  await writeFile(CSS_OUT, css, 'utf8');

  const total = all.reduce((n, f) => n + f.bytes, 0);
  console.log(`\n${all.length} files, ${(total / 1024).toFixed(0)} KB total`);
  console.log(`css  -> src/styles/fonts.css`);

  // The two faces that render the hero get preloaded in index.html; print them
  // so the markup and the generated filenames cannot drift apart.
  const preload = all.filter(
    (f) => f.subset === 'latin' && (f.family === 'Newsreader' || f.family === 'Instrument Sans'),
  );
  console.log('\npreload these in index.html:');
  for (const f of preload) console.log(`  /fonts/${f.file}  (${f.family} ${f.weight})`);
}

main().catch((err) => {
  console.error('\nFailed:', err.message);
  console.error('Fonts are committed to the repo, so this only needs to run when the set changes.');
  process.exit(1);
});
